spring:
  config:
    name: CONFIG-PROD

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
